### ISSUE TITLE
No FPV from OSMO

### ISSUE THREAD

**Issue by skoif** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo-Swift#2]
- Camera: DJI OSMO with zenmuse x3
- Device: Iphone X
- IOS 11.2.2

When I upload this app to my phone and starts it, nothing happens. Just black screen with control elements.

UPD: control elements (buttons located at the bottom) are not reacting to osmo actions (for example: pressing real rec button)

**Comment by oliverou** [comment]
Hi @skoif, Since OSMO use WiFi connection, please check the following steps:
1. Make sure you have applied for an App Key from DJI developer website and fill it in the info.plist file;
1. Make sure your iPhone X connects to the internet first time when it launches to register the FPVDemo application successfully.
2. Switch the iPhone X's wifi connection to OSMO and you should see the live video feed from the Zenmuse X3 camera.

For more details, please check the tutorial: <https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/index.html>
